# Generated by Django 3.2.23 on 2024-05-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='laptops/%Y/%m/'),
        ),
    ]
